# Generated by Django 6.0.2 on 2026-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('seats', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
