# Generated by Django 6.0.2 on 2026-02-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
