# Generated by Django 6.0.2 on 2026-02-21 18:29

import menu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_ingredients_menuitem_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[menu.validators.validate_menuitem_price]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, validators=[menu.validators.validate_menuitem_title]),
        ),
    ]
