# Generated by Django 6.0.2 on 2026-02-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_time',
        ),
    ]
